name: Deploy DESA

on:
  push:
    branches:
      - desa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DESA
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DESA_SERVER_IP }}
          username: ${{ secrets.DESA_SERVER_USER }}
          key: ${{ secrets.DESA_SSH_PRIVATE_KEY }}
          script: |
            /home/${{ secrets.DESA_SERVER_USER }}/sh/deploy.sh desa ${{ secrets.DESA_SERVER_USER }}